export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    GETTOKEN_REQUEST: 'GETTOKEN_REQUEST',
    GETTOKEN_SUCCESS: 'GETTOKEN_SUCCESS',
    GETTOKEN_FAILURE: 'GETTOKEN_FAILURE',
    GETUSER_REQUEST: 'GETUSER_REQUEST',
    GETUSER_SUCCESS: 'GETUSER_SUCCESS',
    GETUSER_FAILURE: 'GETUSER_FAILURE',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILURE: 'GET_ALL_USER_FAILURE',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    DELETE_ACCOUNT_BY_ID_REQUEST: 'DELETE_ACCOUNT_BY_ID_REQUEST',
    DELETE_ACCOUNT_BY_ID_SUCCESS: 'DELETE_ACCOUNT_BY_ID_SUCCESS',
    DELETE_ACCOUNT_BY_ID_FAILURE: 'DELETE_ACCOUNT_BY_ID_FAILURE'
};

export const actionConstants = {
    GET_ALL_ACTION_REQUEST: 'GET_ALL_ACTION_REQUEST',
    GET_ALL_ACTION_SUCCESS: 'GET_ALL_ACTION_SUCCESS',
    GET_ALL_ACTION_FAILURE: 'GET_ALL_ACTION_FAILURE',
    CREATE_ACTION_REQUEST: 'CREATE_ACTION_REQUEST',
    CREATE_ACTION_SUCCESS: 'CREATE_ACTION_SUCCESS',
    CREATE_ACTION_FAILURE: 'CREATE_ACTION_FAILURE',
    DELETE_ACTION_BY_ID_REQUEST: 'DELETE_ACTION_BY_ID_REQUEST',
    DELETE_ACTION_BY_ID_SUCCESS: 'DELETE_ACTION_BY_ID_SUCCESS',
    DELETE_ACTION_BY_ID_FAILURE: 'DELETE_ACTION_BY_ID_FAILURE',
    UPDATE_ACTION_REQUEST: 'UPDATE_ACTION_REQUEST',
    UPDATE_ACTION_SUCCESS: 'UPDATE_ACTION_SUCCESS',
    UPDATE_ACTION_FAILURE: 'UPDATE_ACTION_FAILURE'
};

export const roleactionConstants = {
    GET_ALL_ROLEACTION_REQUEST: 'GET_ALL_ROLEACTION_REQUEST',
    GET_ALL_ROLEACTION_SUCCESS: 'GET_ALL_ROLEACTION_SUCCESS',
    GET_ALL_ROLEACTION_FAILURE: 'GET_ALL_ROLEACTION_FAILURE',
    CREATE_ROLEACTION_REQUEST: 'CREATE_ROLEACTION_REQUEST',
    CREATE_ROLEACTION_SUCCESS: 'CREATE_ROLEACTION_SUCCESS',
    CREATE_ROLEACTION_FAILURE: 'CREATE_ROLEACTION_FAILURE',
    DELETE_ROLEACTION_BY_ID_REQUEST: 'DELETE_ROLEACTION_BY_ID_REQUEST',
    DELETE_ROLEACTION_BY_ID_SUCCESS: 'DELETE_ROLEACTION_BY_ID_SUCCESS',
    DELETE_ROLEACTION_BY_ID_FAILURE: 'DELETE_ROLEACTION_BY_ID_FAILURE',
    UPDATE_ROLEACTION_REQUEST: 'UPDATE_ROLEACTION_REQUEST',
    UPDATE_ROLEACTION_SUCCESS: 'UPDATE_ROLEACTION_SUCCESS',
    UPDATE_ROLEACTION_FAILURE: 'UPDATE_ROLEACTION_FAILURE'
};

export const tagConstants = {
    GET_ALL_TAG_REQUEST: 'GET_ALL_TAG_REQUEST',
    GET_ALL_TAG_SUCCESS: 'GET_ALL_TAG_SUCCESS',
    GET_ALL_TAG_FAILURE: 'GET_ALL_TAG_FAILURE',
    CREATE_TAG_REQUEST: 'CREATE_TAG_REQUEST',
    CREATE_TAG_SUCCESS: 'CREATE_TAG_SUCCESS',
    CREATE_TAG_FAILURE: 'CREATE_TAG_FAILURE',
    DELETE_TAG_BY_ID_REQUEST: 'DELETE_TAG_BY_ID_REQUEST',
    DELETE_TAG_BY_ID_SUCCESS: 'DELETE_TAG_BY_ID_SUCCESS',
    DELETE_TAG_BY_ID_FAILURE: 'DELETE_TAG_BY_ID_FAILURE',
    UPDATE_TAG_REQUEST: 'UPDATE_TAG_REQUEST',
    UPDATE_TAG_SUCCESS: 'UPDATE_TAG_SUCCESS',
    UPDATE_TAG_FAILURE: 'UPDATE_TAG_FAILURE'
};

export const infoProductConstants = {
    GET_ALL_INFO_PRODUCT_REQUEST: 'GET_ALL_INFO_PRODUCT_REQUEST',
    GET_ALL_INFO_PRODUCT_SUCCESS: 'GET_ALL_INFO_PRODUCT_SUCCESS',
    GET_ALL_INFO_PRODUCT_FAILURE: 'GET_ALL_INFO_PRODUCT_FAILURE',
    CREATE_INFO_PRODUCT_REQUEST: 'CREATE_INFO_PRODUCT_REQUEST',
    CREATE_INFO_PRODUCT_SUCCESS: 'CREATE_INFO_PRODUCT_SUCCESS',
    CREATE_INFO_PRODUCT_FAILURE: 'CREATE_INFO_PRODUCT_FAILURE',
    DELETE_INFO_PRODUCT_BY_ID_REQUEST: 'DELETE_INFO_PRODUCT_BY_ID_REQUEST',
    DELETE_INFO_PRODUCT_BY_ID_SUCCESS: 'DELETE_INFO_PRODUCT_BY_ID_SUCCESS',
    DELETE_INFO_PRODUCT_BY_ID_FAILURE: 'DELETE_INFO_PRODUCT_BY_ID_FAILURE',
    UPDATE_INFO_PRODUCT_REQUEST: 'UPDATE_INFO_PRODUCT_REQUEST',
    UPDATE_INFO_PRODUCT_SUCCESS: 'UPDATE_INFO_PRODUCT_SUCCESS',
    UPDATE_INFO_PRODUCT_FAILURE: 'UPDATE_INFO_PRODUCT_FAILURE'
};

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_CHANGE_STATE_SUCCESS: 'USER_CHANGE_STATE_SUCCESS'
};
export const bannerConstants = {
    GET_ALL_BANNER_REQUEST: 'GET_ALL_BANNER_REQUEST',
    GET_ALL_BANNER_SUCCESS: 'GET_ALL_BANNER_SUCCESS',
    GET_ALL_BANNER_FAILURE: 'GET_ALL_BANNER_FAILURE',
    CREATE_BANNER_REQUEST: 'CREATE_BANNER_REQUEST',
    CREATE_BANNER_SUCCESS: 'CREATE_BANNER_SUCCESS',
    CREATE_BANNER_FAILURE: 'CREATE_BANNER_FAILURE',
    DELETE_BANNER_BY_ID_REQUEST: 'DELETE_BANNER_BY_ID_REQUEST',
    DELETE_BANNER_BY_ID_SUCCESS: 'DELETE_BANNER_BY_ID_SUCCESS',
    DELETE_BANNER_BY_ID_FAILURE: 'DELETE_BANNER_BY_ID_FAILURE',
    UPDATE_BANNER_REQUEST: 'UPDATE_BANNER_REQUEST',
    UPDATE_BANNER_SUCCESS: 'UPDATE_BANNER_SUCCESS',
    UPDATE_BANNER_FAILURE: 'UPDATE_BANNER_FAILURE'
};
export const roleConstants = {
    CREATE_ROLE_REQUEST: 'CREATE_ROLE_REQUEST',
    CREATE_ROLE_SUCCESS: 'CREATE_ROLE_SUCCESS',
    CREATE_ROLE_FAILURE: 'CREATE_ROLE_FAILURE',
    GET_ALL_ROLE_REQUEST: 'GET_ALL_ROLE_REQUEST',
    GET_ALL_ROLE_SUCCESS: 'GET_ALL_ROLE_SUCCESS',
    GET_ALL_ROLE_FAILURE: 'GET_ALL_ROLE_FAILURE',
    UPDATE_ROLE_REQUEST: 'UPDATE_ROLE_REQUEST',
    UPDATE_ROLE_SUCCESS: 'UPDATE_ROLE_SUCCESS',
    UPDATE_ROLE_FAILURE: 'UPDATE_ROLE_FAILURE',
    DELETE_ROLE_REQUEST: 'DELETE_ROLE_REQUEST',
    DELETE_ROLE_SUCCESS: 'DELETE_ROLE_SUCCESS',
    DELETE_ROLE_FAILURE: 'DELETE_ROLE_FAILURE',
    DELETE_ROLE_BY_ID_REQUEST: 'DELETE_ROLE_BY_ID_REQUEST',
    DELETE_ROLE_BY_ID_SUCCESS: 'DELETE_ROLE_BY_ID_SUCCESS',
    DELETE_ROLE_BY_ID_FAILURE: 'DELETE_ROLE_BY_ID_FAILURE'
};
export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
    ADD_NEW_CATEGORIES_SUCCESS: 'ADD_NEW_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORIES_FAILURE: 'ADD_NEW_CATEGORIES_FAILURE',
    UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',
    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE'
};
export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
};
export const productConstants = {
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',
    DELETE_PRODUCT_BY_ID_REQUEST: 'DELETE_PRODUCT_BY_ID_REQUEST',
    DELETE_PRODUCT_BY_ID_SUCCESS: 'DELETE_PRODUCT_BY_ID_SUCCESS',
    DELETE_PRODUCT_BY_ID_FAILURE: 'DELETE_PRODUCT_BY_ID_FAILURE',

    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
    ADD_PRODUCT_NOT_ENOUGH_ROLE: 'ADD_PRODUCT_NOT_ENOUGH_ROLE',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
    GET_PRODUCT_DETAILS_BY_ID_REQUEST: 'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: 'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: 'GET_PRODUCT_DETAILS_BY_ID_FAILURE'
};
export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE',
    GET_ALL_PAGE_REQUEST: 'GET_ALL_PAGE_REQUEST',
    GET_ALL_PAGE_SUCCESS: 'GET_ALL_PAGE_SUCCESS',
    GET_ALL_PAGE_FAILURE: 'GET_ALL_PAGE_FAILURE'
};
export const screenConstants = {
    GET_ALL_SCREEN_SUCCESS: 'GET_ALL_SCREEN_SUCCESS',
    GET_ALL_SCREEN_REQUEST: 'GET_ALL_SCREEN_REQUEST',
    GET_ALL_SCREEN_FAILURE: 'GET_ALL_SCREEN_FAILURE',
    CREATE_SCREEN_SUCCESS: 'CREATE_SCREEN_SUCCESS',
    CREATE_SCREEN_REQUEST: 'CREATE_SCREEN_REQUEST',
    CREATE_SCREEN_FAILURE: 'CREATE_SCREEN_FAILURE',
    DELETE_SCREEN_BY_ID_REQUEST: 'DELETE_SCREEN_BY_ID_REQUEST',
    DELETE_SCREEN_BY_ID_SUCCESS: 'DELETE_SCREEN_BY_ID_SUCCESS',
    DELETE_SCREEN_BY_ID_FAILURE: 'DELETE_SCREEN_BY_ID_FAILURE',
    UPDATE_SCREEN_REQUEST: 'UPDATE_SCREEN_REQUEST',
    UPDATE_SCREEN_SUCCESS: 'UPDATE_SCREEN_SUCCESS',
    UPDATE_SCREEN_FAILURE: 'UPDATE_SCREEN_FAILURE'
};
export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: 'GET_CUSTOMER_ORDER_REQUEST',
    GET_CUSTOMER_ORDER_SUCCESS: 'GET_CUSTOMER_ORDER_SUCCESS',
    GET_CUSTOMER_ORDER_FAILURE: 'GET_CUSTOMER_ORDER_FAILURE',
    GET_ALL_ORDER_SUCCESS: 'GET_ALL_ORDER_SUCCESS',
    GET_ALL_ORDER_REQUEST: 'GET_ALL_ORDER_REQUEST',
    GET_ALL_ORDER_FAILURE: 'GET_ALL_ORDER_FAILURE',
    UPDATE_CUSTOMER_ORDER_REQUEST: 'UPDATE_CUSTOMER_ORDER_REQUEST',
    UPDATE_CUSTOMER_ORDER_SUCCESS: 'UPDATE_CUSTOMER_ORDER_SUCCESS',
    UPDATE_CUSTOMER_ORDER_FAILURE: 'UPDATE_CUSTOMER_ORDER_FAILURE',
    DELETE_ORDER_REQUEST: 'DELETE_ORDER_REQUEST',
    DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
    DELETE_ORDER_FAILURE: 'DELETE_ORDER_FAILURE'
};
